version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000" # Forward container's 3000 port to host's 80 port
    volumes:
      - .:/usr/src/app # Update the volume to match the working directory in Dockerfile
    restart: always
