version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000" # Forward container's 3000 port to host's 80 port
    environment:
      - PORT=3000 # Set the port for the app
    restart: unless-stopped # Ensures the service restarts unless explicitly stopped
    command: ["npm", "run", "dev"] # Override the default CMD from the Dockerfile
